#Adding in comment to trigger commit

version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
      # not supported in the free plan
      # docker_layer_caching: true
    working_directory: ~/go/src/github.com/theupdateframework/notary
    environment:
      DOCKER_BUILDKIT: 1
    steps:
      - add_ssh_keys
      - checkout
#      - artifactory/install
#      - artifactory/configure
#      - artifactory/build-integration
      - run:
          name: "Docker Info"
          command: |
            docker version
            docker info
      - run:
          name: Check vendor modules
          command: ./buildscripts/circle-validate-vendor.sh
      - run:
          name: "Build image"
          command: docker build --progress=plain -t notary_client .
#      - run: ./buildscripts/circle_parallelism.sh
      - run: docker-compose -f docker-compose.yml down -v && docker-compose -f docker-compose.rethink.yml down -v
      - run: docker image ls      
      - run: 
           name: docker login
           command: |
             echo "$DOCKER_PASSWORD" | \
               docker login --username "$DOCKER_LOGIN" --password-stdin 
      - run: docker push 
#orbs:
#  artifactory: circleci/artifactory@1.0.0
#version: 2.1
workflows:
  custom-docker-example:
    jobs:
      - build
#      - artifactory/docker-publish:
#          docker-registry: orbdemos-docker-local.jfrog.io
#          docker-steps:
#            - run: docker build -t $DOCKERTAG docker-publish-assets
#          docker-tag: >-
#            orbdemos-docker-local.jfrog.io/hello-world-custom:1.0-${CIRCLE_BUILD_NUM}
#          name: Docker Publish Custom Build
#          repository: docker-local
